### PR TITLE
#279 UWP server and channel zero state

### LINKED ISSUE #279: 💙 - UWP Server/Channel zero state
> 🟥🟩 **WINDOWS 10** - Version 1903+ is required for the UWP UI.
> 🟦🟨 [How to setup UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-set-up)

## Summary

When the user views the Servers or Channels section of our UWP app and the bot isn't in any server or channels, the view looks a bit weird:

image

The Discord client for a reference has a cheeky zero state for this:

image

> ℹ️ Same goes for no servers.

## How to implement

We could go as simple as just displaying:

`There are no servers to browse.` and `This server doesn't contain any channels.`.

Or we could go as complex as creating our own zero-states like Discord. Either way is fine. 😊 

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[Discord](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

### PR DESCRIPTION
**Pull request by 1n5an1ty**
## Related Issue

Fixes #279 

## Changes
Add 'Servers' page zero/no state page content
Update ServersPageViewModel
Add 'Channel' page zero/no state page content
Remove unused page-level references

## Expected Feedback
General code review and basic 5an1ty checks

### CODE REVIEW

**Comment by 1n5an1ty** [comment]
I just wanted to let you guys know that I am still working on this. Researching a way to consolidate the UI code duplication in the two zero/no state display screens. I believe we could use something equivalent to a user control to accomplish this, but I need to figure out what UWP plays nice with.

**Comment by 1n5an1ty** [comment]
Has anyone had a chance to test this on another Windows machine?

**Comment by DraxCodes** [comment]
> 
> 
> Has anyone had a chance to test this on another Windows machine?

I haven't but will try get it tested this evening. 😃

**Comment by petrspelos** [comment]
Work flawlessly on my Windows 10 - 1909 build 18363.778.

Amazing work, @1n5an1ty! Thank you so much. ❤️ 

image

Not going to lie, our application is shaping up to be really good!

**Pull request merged**
