### PR TITLE
Update TokenValidator.cs

### PR DESCRIPTION
**Pull request by svr333**
Adding an extra check that's always true. Yes, I'm aware this comes out of the blue.

### CODE REVIEW

**Comment by svr333** [comment]
Its just an extra validation, it'll probably never have a use case but we can use it to be even more sure it is a valid token.

Also, I didn't check the tests but I'm 100% sure the checks still pass. I literally changed nothing besides an actual check that's always true with a real Discord bot token.

**Comment by DraxCodes** [comment]
> 
> 
> Its just an extra validation, it'll probably never have a use case but we can use it to be even more sure it is a valid token.
> 
> Also, I didn't check the tests but I'm 100% sure the checks still pass. I literally changed nothing besides an actual check that's always true with a real Discord bot token.

Would you mind running the tests just to be sure please ma dude? :)

No rush for it but just to be sure.

**Comment by svr333** [comment]
Yeah, I'll do it tomorrow morning, that is if I do not forget to.

**Comment by svr333** [comment]
@DraxCodes, all tests pass.

**Pull request merged**
