### PR TITLE
Uwp send messages

### LINKED ISSUE #202: 💙 - Send messages to channels
> 🟥🟩 **WINDOWS 10** - Version 1903+ is required for the UWP UI.
> 🟦🟨 [How to setup UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-set-up)

## Summary

The user can view messages from different channels, but they cannot send one. This feature would allow them to send messages (as Miunie) into different channels from the same view.

image

## What needs to be done

The `ServersPage` view should get a new input box and a "send" button. When the user fills the input and hits send, Miunie sends their message into the currently viewed Discord channel.

## Technical notes

- 📁 **Miunie.Discord**
    - 📄 Impersonation.cs

The `IDiscordImpersonation` (from `Miunie.Core`) and the implementation `Impersonation.cs` (from `Miunie.Discord`) should get a new method that would allow for a `string` to be posted into a channel based on a `ulong` channel id. (Server id can be added as well if it turns out to be required).

- 📁 **Miunie.WindowsApp**
    - 📁 Views
        - 📄 ImpersonationChatPage

The chat page view in UWP will need new UI elements to get the needed information from the user.

- 📁 **Miunie.WindowsApp**
    - 📁 ViewModel
        - 📄 ImpersonationChatPageViewModel.cs

The `ImpersonationChatPageViewModel` already demonstrates an interaction with the impersonation class. New code would be added into the `ImpersonationChatPageViewModel` class to achieve the desired behavior.

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[Discord](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

### PR DESCRIPTION
**Pull request by petrspelos**
## Related Issue

Fixes #202 #241 

## Changes
- Add a new `SendTextToChannelAsync` method to the Impersonation object
- Implement a UI for sending texts to channel
- Add bi-directional message support

## Expected Feedback
Yeah, I'm not a 100% on the way I get to the `TextBox`, the problem is that I can't just give it a Name, since it's inside a DataTemplate. My way of getting it is quite rigid, so if anyone knows about a better approach, let's hear it. 😊 

Other than that, general sanity checks. 🙌 

Also if someone could try it out on their machine, that would be great. 😊

### CODE REVIEW

**Comment by petrspelos** [comment]
Thank you, @1n5an1ty!

I'll take a look at the resources you mentioned.

bitmoji

**Comment by 1n5an1ty** [comment]
Here is another good resource: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/commanding

**Comment by petrspelos** [comment]
@1n5an1ty I fixed a null reference exception that I encountered, however, it looks like listening for new messages causes the list to play its opening animation every time it gets a message.

example

**Comment by 1n5an1ty** [comment]
https://github.com/control-net/Miunie/pull/237#issuecomment-593902823 I noticed this as well. Due to the nesting... It's reloading the entire channel, I will try and make this more dynamic.

**Comment by 1n5an1ty** [comment]
Do not approve this yet... I have created a better solution.

**Comment by 1n5an1ty** [comment]
This is ready for review. Please run and test it locally as well as normal 5an1ty checks.

**Comment by petrspelos** [comment]
Works on my Windows 10 1909.
Great job! 🎉

**Pull request merged**
