### PR TITLE
Commands switch

### PR DESCRIPTION
**Pull request by MNiekel**
## Related Issue
Commands Switch - Avalonia UI #280

Fixes # 280

## Changes
Added a checkbox with binding to toggle enable commands

### CODE REVIEW

**Comment by MNiekel** [comment]
Oh, ups, I see did not correct my changes on he profile title issue, sorry.

**Comment by 1n5an1ty** [comment]
> Oh, ups, I see did not correct my changes on he profile title issue, sorry.

Just making

**Comment by MNiekel** [comment]
I'll close this pull request and remove my changes from the other issue and then make a new pull request, is that ok?

**Comment by 1n5an1ty** [comment]
You don't need to close your PR, just update it by making more commits to this branch in your repo.

**Pull request closed without merging**
